package com.livefutar.app.util

/**
 * Teljesebb magyar névfordító – országok, bajnokságok, csapatok.
 * Ismeretlen neveket változtatás nélkül adja vissza.
 */
object HungarianNames {

    // ── Országok ──────────────────────────────────────────────────────────
    private val countries = mapOf(
        // Európa
        "England" to "Anglia",
        "Spain" to "Spanyolország",
        "Italy" to "Olaszország",
        "Germany" to "Németország",
        "France" to "Franciaország",
        "Portugal" to "Portugália",
        "Netherlands" to "Hollandia",
        "Holland" to "Hollandia",
        "Belgium" to "Belgium",
        "Turkey" to "Törökország",
        "Turkiye" to "Törökország",
        "Türkiye" to "Törökország",
        "Scotland" to "Skócia",
        "Wales" to "Wales",
        "Ireland" to "Írország",
        "Republic of Ireland" to "Írország",
        "Northern Ireland" to "Észak-Írország",
        "Austria" to "Ausztria",
        "Switzerland" to "Svájc",
        "Poland" to "Lengyelország",
        "Czech Republic" to "Csehország",
        "Czechia" to "Csehország",
        "Slovakia" to "Szlovákia",
        "Hungary" to "Magyarország",
        "Romania" to "Románia",
        "Bulgaria" to "Bulgária",
        "Serbia" to "Szerbia",
        "Croatia" to "Horvátország",
        "Slovenia" to "Szlovénia",
        "Bosnia and Herzegovina" to "Bosznia-Hercegovina",
        "Bosnia" to "Bosznia-Hercegovina",
        "Montenegro" to "Montenegró",
        "North Macedonia" to "Észak-Macedónia",
        "Macedonia" to "Észak-Macedónia",
        "Albania" to "Albánia",
        "Greece" to "Görögország",
        "Denmark" to "Dánia",
        "Sweden" to "Svédország",
        "Norway" to "Norvégia",
        "Finland" to "Finnország",
        "Iceland" to "Izland",
        "Russia" to "Oroszország",
        "Ukraine" to "Ukrajna",
        "Belarus" to "Fehéroroszország",
        "Georgia" to "Grúzia",
        "Armenia" to "Örményország",
        "Azerbaijan" to "Azerbajdzsán",
        "Kazakhstan" to "Kazahsztán",
        "Uzbekistan" to "Üzbegisztán",
        "Israel" to "Izrael",
        "Latvia" to "Lettország",
        "Lithuania" to "Litvánia",
        "Estonia" to "Észtország",
        "Moldova" to "Moldova",
        "Cyprus" to "Ciprus",
        "Kosovo" to "Koszovó",
        "Malta" to "Málta",
        "Luxembourg" to "Luxemburg",
        "Andorra" to "Andorra",
        "San Marino" to "San Marino",
        "Faroe Islands" to "Feröer-szigetek",

        "Republic of Ireland" to "Írország",
        "Rep of Ireland" to "Írország",
        "Rep. of Ireland" to "Írország",
        "Northern Ireland" to "Észak-Írország",
        "N. Ireland" to "Észak-Írország",
        "Bosnia & Herzegovina" to "Bosznia-Hercegovina",
        "Bosnia-Herzegovina" to "Bosznia-Hercegovina",
        "North Macedonia" to "Észak-Macedónia",
        "FYR Macedonia" to "Észak-Macedónia",
        "Macedonia" to "Észak-Macedónia",
        "Faroe Islands" to "Feröer-szigetek",
        "Faeroe Islands" to "Feröer-szigetek",
        "Czech Republic" to "Csehország",
        "Czechia" to "Csehország",
        "The Netherlands" to "Hollandia",
        "Holland" to "Hollandia",
        "USA" to "USA",
        "United States" to "USA",
        "South Korea" to "Dél-Korea",
        "Korea Republic" to "Dél-Korea",
        "Ivory Coast" to "Elefántcsontpart",
        "Côte d'Ivoire" to "Elefántcsontpart",
        "Cote d'Ivoire" to "Elefántcsontpart",

        "Gibraltar" to "Gibraltár",
        // Afrika / Ázsia / Amerika
        "Saudi Arabia" to "Szaúd-Arábia",
        "United Arab Emirates" to "Egyesült Arab Emírségek",
        "UAE" to "Egyesült Arab Emírségek",
        "Qatar" to "Katar",
        "Egypt" to "Egyiptom",
        "Morocco" to "Marokkó",
        "Tunisia" to "Tunézia",
        "Algeria" to "Algéria",
        "South Africa" to "Dél-Afrika",
        "Nigeria" to "Nigéria",
        "Ghana" to "Ghána",
        "Senegal" to "Szenegál",
        "Ivory Coast" to "Elefántcsontpart",
        "Cote d'Ivoire" to "Elefántcsontpart",
        "Cameroon" to "Kamerun",
        "USA" to "USA",
        "United States" to "USA",
        "United States of America" to "USA",
        "Mexico" to "Mexikó",
        "Canada" to "Kanada",
        "Brazil" to "Brazília",
        "Argentina" to "Argentína",
        "Uruguay" to "Uruguay",
        "Chile" to "Chile",
        "Colombia" to "Kolumbia",
        "Peru" to "Peru",
        "Ecuador" to "Ecuador",
        "Paraguay" to "Paraguay",
        "Bolivia" to "Bolívia",
        "Venezuela" to "Venezuela",
        "Japan" to "Japán",
        "South Korea" to "Dél-Korea",
        "Korea Republic" to "Dél-Korea",
        "Korea, Republic of" to "Dél-Korea",
        "China" to "Kína",
        "China PR" to "Kína",
        "Australia" to "Ausztrália",
        "New Zealand" to "Új-Zéland",
        "India" to "India",
        "Iran" to "Irán",
        "Iraq" to "Irak",
        "Jordan" to "Jordánia",
        "Lebanon" to "Libanon",
        "Syria" to "Szíria",
        "Thailand" to "Thaiföld",
        "Vietnam" to "Vietnám",
        "Indonesia" to "Indonézia",
        "Malaysia" to "Malajzia",
        "Singapore" to "Szingapúr",
        "World" to "Világ",
        "Europe" to "Európa",
        "International" to "Nemzetközi",
        "South America" to "Dél-Amerika",
        "Africa" to "Afrika",
        "Asia" to "Ázsia",
        "North America" to "Észak-Amerika",
        "Oceania" to "Óceánia"
    )

    // ── Bajnokságok / kupák ────────────────────────────────────────────────
    private val leagues = mapOf(
        // Top 5
        "Premier League" to "Premier League",
        "English Premier League" to "Premier League",
        "La Liga" to "La Liga",
        "LaLiga" to "La Liga",
        "Serie A" to "Serie A",
        "Bundesliga" to "Bundesliga",
        "1. Bundesliga" to "Bundesliga",
        "Ligue 1" to "Ligue 1",
        // Anglia
        "Championship" to "Championship",
        "EFL Championship" to "Championship",
        "League One" to "League One",
        "League Two" to "League Two",
        "FA Cup" to "FA-kupa",
        "EFL Cup" to "EFL-kupa",
        "Carabao Cup" to "EFL-kupa",
        "Community Shield" to "Community Shield",
        // Spanyolország
        "La Liga 2" to "La Liga 2",
        "Segunda División" to "La Liga 2",
        "Copa del Rey" to "Spanyol Kupa",
        "Supercopa de España" to "Spanyol Szuperkupa",
        // Olaszország
        "Serie B" to "Serie B",
        "Coppa Italia" to "Olasz Kupa",
        "Supercoppa Italiana" to "Olasz Szuperkupa",
        // Németország
        "2. Bundesliga" to "2. Bundesliga",
        "3. Liga" to "3. Liga",
        "DFB Pokal" to "Német Kupa",
        "DFB-Pokal" to "Német Kupa",
        "DFL-Supercup" to "Német Szuperkupa",
        // Franciaország
        "Ligue 2" to "Ligue 2",
        "Coupe de France" to "Francia Kupa",
        "Trophée des Champions" to "Francia Szuperkupa",
        // Portugália / Hollandia / Törökország
        "Primeira Liga" to "Primeira Liga",
        "Liga Portugal" to "Primeira Liga",
        "Eredivisie" to "Eredivisie",
        "Keuken Kampioen Divisie" to "Eerste Divisie",
        "Super Lig" to "Süper Lig",
        "Süper Lig" to "Süper Lig",
        // UEFA / FIFA
        "UEFA Champions League" to "Bajnokok Ligája",
        "Champions League" to "Bajnokok Ligája",
        "UEFA Europa League" to "Európa Liga",
        "Europa League" to "Európa Liga",
        "UEFA Europa Conference League" to "Konferencia Liga",
        "Europa Conference League" to "Konferencia Liga",
        "Conference League" to "Konferencia Liga",
        "UEFA Super Cup" to "UEFA-szuperkupa",
        "UEFA Nations League" to "Nemzetek Ligája",
        "FIFA World Cup" to "Világbajnokság",
        "World Cup" to "Világbajnokság",
        "FIFA Club World Cup" to "Klubvilágbajnokság",
        "Club World Cup" to "Klubvilágbajnokság",
        "European Championship" to "Európa-bajnokság",
        "Euro" to "Európa-bajnokság",
        "UEFA Euro" to "Európa-bajnokság",
        // Magyarország
        "NB I" to "NB I",
        "OTP Bank Liga" to "NB I",
        "NB 1" to "NB I",
        "NB II" to "NB II",
        "NB 2" to "NB II",
        "Magyar Kupa" to "Magyar Kupa",
        "Hungarian Cup" to "Magyar Kupa",
        "Hungarian NB I" to "NB I",
        // Egyéb Európa
        "Scottish Premiership" to "Skót Premiership",
        "Premiership" to "Premiership",
        "Belgian Pro League" to "Belga Pro League",
        "Jupiler Pro League" to "Belga Pro League",
        "Swiss Super League" to "Svájci Szuperliga",
        "Austrian Bundesliga" to "Osztrák Bundesliga",
        "Admiral Bundesliga" to "Osztrák Bundesliga",
        "Ekstraklasa" to "Ekstraklasa",
        "Allsvenskan" to "Allsvenskan",
        "Eliteserien" to "Eliteserien",
        "Danish Superliga" to "Dán Superliga",
        "Superliga" to "Szuperliga",
        "1. HNL" to "1. HNL",
        "HNL" to "1. HNL",
        "Fortuna Liga" to "Fortuna Liga",
        "Chance Liga" to "Chance Liga",
        "Niké Liga" to "Niké Liga",
        "Liga I" to "Liga I",
        "Superliga Serbia" to "Szerb Szuperliga",
        "Mozzart Bet Superliga" to "Szerb Szuperliga",
        // Amerika / egyéb
        "MLS" to "MLS",
        "Major League Soccer" to "MLS",
        "Liga MX" to "Liga MX",
        "Brasileirão" to "Brasileirão",
        "Serie A Brazil" to "Brasileirão",
        "Argentine Primera División" to "Argentin Primera",
        "Liga Profesional" to "Argentin Primera",
        "Saudi Pro League" to "Szaúdi Pro League",
        "A-League" to "A-League",
        "J1 League" to "J1 League",
        "K League 1" to "K League 1",
        "Chinese Super League" to "Kínai Szuperliga",
        "Copa Libertadores" to "Copa Libertadores",
        "Copa Sudamericana" to "Copa Sudamericana",
        "CONCACAF Champions Cup" to "CONCACAF Bajnokok Kupája",
        "African Champions League" to "Afrikai Bajnokok Ligája",
        "CAF Champions League" to "Afrikai Bajnokok Ligája"
    )

    // ── Csapatok (gyakori / top + magyar) ──────────────────────────────────
    private val teams = mapOf(
        // Anglia
        "Manchester United" to "Manchester United",
        "Manchester City" to "Manchester City",
        "Liverpool" to "Liverpool",
        "Chelsea" to "Chelsea",
        "Arsenal" to "Arsenal",
        "Tottenham Hotspur" to "Tottenham",
        "Tottenham" to "Tottenham",
        "Newcastle United" to "Newcastle",
        "Newcastle" to "Newcastle",
        "Aston Villa" to "Aston Villa",
        "West Ham United" to "West Ham",
        "West Ham" to "West Ham",
        "Brighton & Hove Albion" to "Brighton",
        "Brighton" to "Brighton",
        "Crystal Palace" to "Crystal Palace",
        "Everton" to "Everton",
        "Wolverhampton Wanderers" to "Wolverhampton",
        "Wolves" to "Wolverhampton",
        "Fulham" to "Fulham",
        "Brentford" to "Brentford",
        "Nottingham Forest" to "Nottingham Forest",
        "Bournemouth" to "Bournemouth",
        "AFC Bournemouth" to "Bournemouth",
        "Leicester City" to "Leicester",
        "Leicester" to "Leicester",
        "Leeds United" to "Leeds",
        "Leeds" to "Leeds",
        "Southampton" to "Southampton",
        "Ipswich Town" to "Ipswich",
        "Burnley" to "Burnley",
        "Sheffield United" to "Sheffield United",
        // Spanyolország
        "Real Madrid" to "Real Madrid",
        "FC Barcelona" to "Barcelona",
        "Barcelona" to "Barcelona",
        "Atletico Madrid" to "Atlético Madrid",
        "Atlético Madrid" to "Atlético Madrid",
        "Atletico de Madrid" to "Atlético Madrid",
        "Sevilla" to "Sevilla",
        "Real Sociedad" to "Real Sociedad",
        "Athletic Club" to "Athletic Bilbao",
        "Athletic Bilbao" to "Athletic Bilbao",
        "Villarreal" to "Villarreal",
        "Real Betis" to "Real Betis",
        "Valencia" to "Valencia",
        "Osasuna" to "Osasuna",
        "Celta Vigo" to "Celta Vigo",
        "Girona" to "Girona",
        "Getafe" to "Getafe",
        "Mallorca" to "Mallorca",
        "Rayo Vallecano" to "Rayo Vallecano",
        "Espanyol" to "Espanyol",
        "Las Palmas" to "Las Palmas",
        "Alaves" to "Alavés",
        "Alavés" to "Alavés",
        "Cadiz" to "Cádiz",
        "Cádiz" to "Cádiz",
        // Olaszország
        "Inter" to "Inter",
        "Inter Milan" to "Inter",
        "FC Internazionale Milano" to "Inter",
        "AC Milan" to "AC Milan",
        "Milan" to "AC Milan",
        "Juventus" to "Juventus",
        "Napoli" to "Napoli",
        "SSC Napoli" to "Napoli",
        "AS Roma" to "Roma",
        "Roma" to "Roma",
        "Lazio" to "Lazio",
        "SS Lazio" to "Lazio",
        "Atalanta" to "Atalanta",
        "Fiorentina" to "Fiorentina",
        "Torino" to "Torino",
        "Bologna" to "Bologna",
        "Udinese" to "Udinese",
        "Sassuolo" to "Sassuolo",
        "Genoa" to "Genoa",
        "Cagliari" to "Cagliari",
        "Empoli" to "Empoli",
        "Monza" to "Monza",
        "Lecce" to "Lecce",
        "Verona" to "Verona",
        "Hellas Verona" to "Verona",
        // Németország
        "Bayern Munich" to "Bayern München",
        "Bayern München" to "Bayern München",
        "FC Bayern München" to "Bayern München",
        "FC Bayern Munich" to "Bayern München",
        "Borussia Dortmund" to "Dortmund",
        "Dortmund" to "Dortmund",
        "RB Leipzig" to "RB Leipzig",
        "Bayer Leverkusen" to "Leverkusen",
        "Leverkusen" to "Leverkusen",
        "Eintracht Frankfurt" to "Frankfurt",
        "Wolfsburg" to "Wolfsburg",
        "VfL Wolfsburg" to "Wolfsburg",
        "Borussia Mönchengladbach" to "Mönchengladbach",
        "Borussia Monchengladbach" to "Mönchengladbach",
        "Hoffenheim" to "Hoffenheim",
        "TSG Hoffenheim" to "Hoffenheim",
        "Freiburg" to "Freiburg",
        "SC Freiburg" to "Freiburg",
        "Union Berlin" to "Union Berlin",
        "1. FC Union Berlin" to "Union Berlin",
        "Stuttgart" to "Stuttgart",
        "VfB Stuttgart" to "Stuttgart",
        "Mainz" to "Mainz",
        "Mainz 05" to "Mainz",
        "1. FSV Mainz 05" to "Mainz",
        "Augsburg" to "Augsburg",
        "FC Augsburg" to "Augsburg",
        "Werder Bremen" to "Werder Bremen",
        "Heidenheim" to "Heidenheim",
        "Bochum" to "Bochum",
        "FC St. Pauli" to "St. Pauli",
        "Holstein Kiel" to "Holstein Kiel",
        // Franciaország
        "Paris Saint Germain" to "PSG",
        "Paris Saint-Germain" to "PSG",
        "PSG" to "PSG",
        "Olympique Marseille" to "Marseille",
        "Marseille" to "Marseille",
        "Olympique Lyonnais" to "Lyon",
        "Lyon" to "Lyon",
        "AS Monaco" to "Monaco",
        "Monaco" to "Monaco",
        "Lille" to "Lille",
        "LOSC Lille" to "Lille",
        "Nice" to "Nice",
        "OGC Nice" to "Nice",
        "Rennes" to "Rennes",
        "Stade Rennais" to "Rennes",
        "Lens" to "Lens",
        "RC Lens" to "Lens",
        "Strasbourg" to "Strasbourg",
        "Nantes" to "Nantes",
        "Toulouse" to "Toulouse",
        "Reims" to "Reims",
        "Montpellier" to "Montpellier",
        "Brest" to "Brest",
        // Portugália / Hollandia
        "Benfica" to "Benfica",
        "SL Benfica" to "Benfica",
        "Porto" to "Porto",
        "FC Porto" to "Porto",
        "Sporting CP" to "Sporting Lisszabon",
        "Sporting Lisbon" to "Sporting Lisszabon",
        "Ajax" to "Ajax",
        "AFC Ajax" to "Ajax",
        "PSV" to "PSV Eindhoven",
        "PSV Eindhoven" to "PSV Eindhoven",
        "Feyenoord" to "Feyenoord",
        // Törökország / egyéb Európa
        "Galatasaray" to "Galatasaray",
        "Fenerbahce" to "Fenerbahçe",
        "Fenerbahçe" to "Fenerbahçe",
        "Besiktas" to "Beşiktaş",
        "Beşiktaş" to "Beşiktaş",
        "Trabzonspor" to "Trabzonspor",
        "Celtic" to "Celtic",
        "Rangers" to "Rangers",
        "Shakhtar Donetsk" to "Sahtar Donyeck",
        "Dynamo Kyiv" to "Dinamo Kijev",
        "Dynamo Kiev" to "Dinamo Kijev",
        "Red Star Belgrade" to "Crvena zvezda",
        "Crvena Zvezda" to "Crvena zvezda",
        "Partizan" to "Partizan",
        "Olympiacos" to "Olimbiakósz",
        "Olympiacos Piraeus" to "Olimbiakósz",
        "Panathinaikos" to "Panathinaikósz",
        "PAOK" to "PAOK",
        "Anderlecht" to "Anderlecht",
        "Club Brugge" to "Club Brugge",
        "Young Boys" to "Young Boys",
        "Salzburg" to "Salzburg",
        "Red Bull Salzburg" to "Salzburg",
        "Sparta Prague" to "Sparta Prága",
        "Slavia Prague" to "Slavia Prága",
        "Viktoria Plzen" to "Viktoria Plzeň",
        "Dinamo Zagreb" to "Dinamo Zágráb",
        "Hajduk Split" to "Hajduk Split",
        // Magyarország – NB I / klasszikus
        "Ferencvaros" to "Ferencváros",
        "Ferencváros" to "Ferencváros",
        "Ferencvarosi TC" to "Ferencváros",
        "Ferencvárosi TC" to "Ferencváros",
        "FTC" to "Ferencváros",
        "Fradi" to "Ferencváros",
        "Ujpest" to "Újpest",
        "Újpest" to "Újpest",
        "Ujpest FC" to "Újpest",
        "Újpest FC" to "Újpest",
        "MTK Budapest" to "MTK Budapest",
        "MTK" to "MTK Budapest",
        "Honved" to "Honvéd",
        "Honvéd" to "Honvéd",
        "Budapest Honved" to "Honvéd",
        "Budapest Honvéd" to "Honvéd",
        "Debrecen" to "Debrecen",
        "Debreceni VSC" to "Debrecen",
        "DVSC" to "Debrecen",
        "Puskas Akademia" to "Puskás Akadémia",
        "Puskás Akadémia" to "Puskás Akadémia",
        "Puskas Academy" to "Puskás Akadémia",
        "Fehervar" to "Fehérvár",
        "Fehérvár" to "Fehérvár",
        "Vidi" to "Fehérvár",
        "MOL Fehervar" to "Fehérvár",
        "MOL Fehérvár" to "Fehérvár",
        "Videoton" to "Fehérvár",
        "Zalaegerszeg" to "Zalaegerszeg",
        "Zalaegerszegi TE" to "Zalaegerszeg",
        "ZTE" to "Zalaegerszeg",
        "Kisvarda" to "Kisvárda",
        "Kisvárda" to "Kisvárda",
        "Diosgyor" to "Diósgyőr",
        "Diósgyőr" to "Diósgyőr",
        "Diosgyori VTK" to "Diósgyőr",
        "Diósgyőri VTK" to "Diósgyőr",
        "DVTK" to "Diósgyőr",
        "Paks" to "Paks",
        "Paksi FC" to "Paks",
        "Nyiregyhaza" to "Nyíregyháza",
        "Nyíregyháza" to "Nyíregyháza",
        "Nyiregyhaza Spartacus" to "Nyíregyháza",
        "Gyori ETO" to "Győr",
        "Győri ETO" to "Győr",
        "Gyor" to "Győr",
        "Győr" to "Győr",
        "ETO FC Gyor" to "Győr",
        "Kecskemet" to "Kecskemét",
        "Kecskemét" to "Kecskemét",
        "Kecskemeti TE" to "Kecskemét",
        "Vasas" to "Vasas",
        "Vasas SC" to "Vasas",
        "Haladas" to "Haladás",
        "Haladás" to "Haladás",
        "Szombathelyi Haladas" to "Haladás",
        "Mezokovesd" to "Mezőkövesd",
        "Mezőkövesd" to "Mezőkövesd",
        // Dél-Amerika / egyéb top
        "Flamengo" to "Flamengo",
        "Palmeiras" to "Palmeiras",
        "Santos" to "Santos",
        "Corinthians" to "Corinthians",
        "Sao Paulo" to "São Paulo",
        "São Paulo" to "São Paulo",
        "River Plate" to "River Plate",
        "Boca Juniors" to "Boca Juniors",
        "Al Hilal" to "Al-Hilal",
        "Al-Hilal" to "Al-Hilal",
        "Al Nassr" to "Al-Nassr",
        "Al-Nassr" to "Al-Nassr",
        "Al Ahli" to "Al-Ahli",
        "Al-Ahli" to "Al-Ahli",

        "Sporting Braga" to "Braga",
        "SC Braga" to "Braga",
        "Braga" to "Braga",
        "AZ Alkmaar" to "AZ Alkmaar",
        "Twente" to "Twente",
        "FC Twente" to "Twente",
        "Union Saint-Gilloise" to "Union SG",
        "Genk" to "Genk",
        "KRC Genk" to "Genk",
        "Copenhagen" to "Koppenhága",
        "FC Copenhagen" to "Koppenhága",
        "FC København" to "Koppenhága",
        "Malmo FF" to "Malmö",
        "Malmö FF" to "Malmö",
        "Rosenborg" to "Rosenborg",
        "Bodø/Glimt" to "Bodø/Glimt",
        "Bodo/Glimt" to "Bodø/Glimt",
        "Slovan Bratislava" to "Slovan Pozsony",
        "Sparta Praha" to "Sparta Prága",
        "SK Slavia Praha" to "Slavia Prága",
        "Qarabag" to "Qarabağ",
        "Qarabağ" to "Qarabağ",
        "Maccabi Tel Aviv" to "Maccabi Tel-Aviv",
        "Maccabi Haifa" to "Maccabi Haifa",
        "Ludogorets" to "Ludogorec",
        "FCSB" to "FCSB",
        "CFR Cluj" to "CFR Kolozsvár",
        "Rapid Bucuresti" to "Rapid Bukarest",
        "Dinamo Bucuresti" to "Dinamo Bukarest",
        "Steaua Bucuresti" to "Steaua Bukarest",
        "Wisla Krakow" to "Wisła Kraków",
        "Legia Warsaw" to "Legia Varsó",
        "Legia Warszawa" to "Legia Varsó",
        "Lech Poznan" to "Lech Poznań",
        "Al Ittihad" to "Al-Ittihad",
        "Al-Ittihad" to "Al-Ittihad",
        "Inter Miami" to "Inter Miami",
        "LA Galaxy" to "LA Galaxy",
        "New York City FC" to "New York City",
        "Atlanta United" to "Atlanta United",
    )

    // ── Lookup ────────────────────────────────────────────────────────────

    fun country(name: String?): String {
        if (name.isNullOrBlank()) return ""
        return lookup(countries, name) ?: name
    }

    fun league(name: String?): String {
        if (name.isNullOrBlank()) return "Egyéb mérkőzések"
        return lookup(leagues, name) ?: name
    }

    fun team(name: String?): String {
        if (name.isNullOrBlank()) return "Ismeretlen"
        lookup(teams, name)?.let { return it }
        // Válogatottak gyakran országnévként jönnek az API-ból
        lookup(countries, name)?.let { return it }
        // pl. "England U21", "Spain W" → előtag fordítása
        val trimmed = name.trim()
        val suffixMatch = Regex(
            """^(.+?)\s*(U\d+|W|Women|Men|National Team|NT)$""",
            RegexOption.IGNORE_CASE
        ).find(trimmed)
        if (suffixMatch != null) {
            val base = suffixMatch.groupValues[1].trim()
            val suffix = suffixMatch.groupValues[2].trim()
            val huBase = lookup(teams, base) ?: lookup(countries, base)
            if (huBase != null) {
                val huSuffix = when {
                    suffix.startsWith("U", ignoreCase = true) -> suffix.uppercase()
                    suffix.equals("W", true) || suffix.equals("Women", true) -> "Női"
                    suffix.equals("Men", true) -> "Férfi"
                    else -> suffix
                }
                return "$huBase $huSuffix"
            }
        }
        return name
    }

    fun display(countryName: String?, leagueName: String?): String {
        val l = league(leagueName)
        val c = country(countryName).takeIf {
            it.isNotBlank() &&
                !it.equals("Világ", true) &&
                !it.equals("World", true) &&
                !it.equals("Nemzetközi", true)
        }
        return if (c != null) "$c · $l" else l
    }

    private fun lookup(map: Map<String, String>, name: String): String? {
        map[name]?.let { return it }
        map.entries.firstOrNull { it.key.equals(name, ignoreCase = true) }?.value?.let { return it }
        // Biztonságos prefix: "Ferencvarosi TC" → Ferencváros, "Manchester United U21" → …
        val lower = name.lowercase().trim()
        if (lower.length < 4) return null
        return map.entries
            .filter { it.key.length >= 4 }
            .filter {
                val k = it.key.lowercase()
                lower.startsWith(k) || k.startsWith(lower)
            }
            .maxByOrNull { it.key.length }
            ?.value
    }
}

